
//['tfc:stone/axe_head/igneous_extrusive', 'tfc:stone/hammer_head/igneous_extrusive', 'tfc:stone/hoe_head/igneous_extrusive', 'tfc:stone/javelin_head/igneous_extrusive', 'tfc:stone/knife_head/igneous_extrusive']
onEvent('tags.items', (event) => {
    rockTypes2.forEach(element => {
        event.add('tfc:shovel_head', `tfc:stone/shovel_head/${element}`)
        event.add('tfc:axe_head', `tfc:stone/axe_head/${element}`)
        event.add('tfc:hammer_head', `tfc:stone/hammer_head/${element}`)
        event.add('tfc:hoe_head', `tfc:stone/hoe_head/${element}`)
        event.add('tfc:javelin_head', `tfc:stone/javelin_head/${element}`)
        event.add('tfc:knife_blade', `tfc:stone/knife_head/${element}`)
    })

    tfcMetalTools.forEach(element => {
        event.add('tfc:shovel_head', `tfc:metal/shovel_head/${element}`)
        event.add('tfc:axe_head', `tfc:metal/axe_head/${element}`)
        event.add('tfc:hammer_head', `tfc:metal/hammer_head/${element}`)
        event.add('tfc:hoe_head', `tfc:metal/hoe_head/${element}`)
        event.add('tfc:javelin_head', `tfc:metal/javelin_head/${element}`)
        event.add('tfc:pickaxe_head', `tfc:metal/pickaxe_head/${element}`)
        event.add('tfc:chisel_head', `tfc:metal/chisel_head/${element}`)
        event.add('tfc:propick_head', `tfc:metal/propick_head/${element}`)
        event.add('tfc:mace_head', `tfc:metal/mace_head/${element}`)
        event.add('tfc:knife_blade', `tfc:metal/knife_blade/${element}`)
        event.add('tfc:sword_blade', `tfc:metal/sword_blade/${element}`)
        event.add('tfc:scythe_blade', `tfc:metal/scythe_blade/${element}`)
        event.add('tfc:saw_blade', `tfc:metal/saw_blade/${element}`)
    })

    tfcMetalToolsHard.forEach(element => {
        event.add('tfc:shovel_head_hard', `tfc:metal/shovel_head/${element}`)
        event.add('tfc:axe_head_hard', `tfc:metal/axe_head/${element}`)
        event.add('tfc:hammer_head_hard', `tfc:metal/hammer_head/${element}`)
        event.add('tfc:hoe_head_hard', `tfc:metal/hoe_head/${element}`)
        event.add('tfc:javelin_head_hard', `tfc:metal/javelin_head/${element}`)
        event.add('tfc:pickaxe_head_hard', `tfc:metal/pickaxe_head/${element}`)
        event.add('tfc:chisel_head_hard', `tfc:metal/chisel_head/${element}`)
        event.add('tfc:propick_head_hard', `tfc:metal/propick_head/${element}`)
        event.add('tfc:mace_head_hard', `tfc:metal/mace_head/${element}`)
        event.add('tfc:knife_blade_hard', `tfc:metal/knife_blade/${element}`)
        event.add('tfc:sword_blade_hard', `tfc:metal/sword_blade/${element}`)
        event.add('tfc:scythe_blade_hard', `tfc:metal/scythe_blade/${element}`)
        event.add('tfc:saw_blade_hard', `tfc:metal/saw_blade/${element}`)
    })

    tfcMetalToolsHard.forEach(element => {
        event.add('tfc:shovel_hard', `tfc:metal/shovel/${element}`)
        event.add('tfc:axe_hard', `tfc:metal/axe/${element}`)
        event.add('tfc:hammer_hard', `tfc:metal/hammer/${element}`)
        event.add('tfc:hoe_hard', `tfc:metal/hoe/${element}`)
        event.add('tfc:javelin_hard', `tfc:metal/javelin/${element}`)
        event.add('tfc:pickaxe_hard', `tfc:metal/pickaxe/${element}`)
        event.add('tfc:chisel_hard', `tfc:metal/chisel/${element}`)
        event.add('tfc:propick_hard', `tfc:metal/propick/${element}`)
        event.add('tfc:mace_hard', `tfc:metal/mace/${element}`)
        event.add('tfc:knife_hard', `tfc:metal/knife/${element}`)
        event.add('tfc:sword_hard', `tfc:metal/sword/${element}`)
        event.add('tfc:scythe_hard', `tfc:metal/scythe/${element}`)
        event.add('tfc:saw_hard', `tfc:metal/saw/${element}`)
    })
})