const framedGlass = [
  'create:framed_glass',
  'create:horizontal_framed_glass',
  'create:vertical_framed_glass',
]

const logTypes = [
  'acacia',
  'ash',
  'aspen',
  'birch',
  'blackwood',
  'chestnut',
  'douglas_fir',
  'hickory',
  'kapok',
  'maple',
  'oak',
  'palm',
  'pine',
  'rosewood',
  'sequoia',
  'spruce',
  'sycamore',
  'white_cedar',
  'willow',
]

const rockTypes = [
  'granite',
  'diorite',
  'gabbro',
  'shale',
  'claystone',
  'limestone',
  'conglomerate',
  'dolomite',
  'chert',
  'chalk',
  'rhyolite',
  'basalt',
  'andesite',
  'dacite',
  'quartzite',
  'slate',
  'phyllite',
  'schist',
  'gneiss',
  'marble',
]

const tfcMetal = [
  'bismuth',
  'bismuth_bronze',
  'black_bronze',
  'bronze',
  'brass',
  'copper',
  'gold',
  'nickel',
  'rose_gold',
  'silver',
  'tin',
  'zinc',
  'sterling_silver',
  'wrought_iron',
  'cast_iron',
  'pig_iron',
  'steel',
  'black_steel',
  'blue_steel',
  'red_steel',
  'weak_steel',
  'weak_blue_steel',
  'weak_red_steel',
  'high_carbon_steel',
  'high_carbon_black_steel',
  'high_carbon_blue_steel',
  'high_carbon_red_steel',
]

// ['tfc:rock/cobble/andesite', 'tfc:rock/cobble/schist', 'tfc:rock/cobble/gabbro', 'tfc:rock/cobble/basalt', 'tfc:rock/cobble/chert', 'tfc:rock/cobble/chalk', 'tfc:rock/cobble/claystone', 'tfc:rock/cobble/conglomerate']

const sandRocks = [
  'claystone',
  'conglomerate',
  'chert',
  'chalk',
  'basalt',
  'andesite',
  'schist',
  'gabbro',
]

const sandColors = [
  'brown',
  'white',
  'black',
  'red',
  'yellow',
  'green',
  'pink',
]
